### ISSUE TITLE
How to disable 3d models

### ISSUE THREAD

**Issue by rozhok** [TheStaticVoid/VoidHUD2.0#1]
Hey, thanks for your work!
All is pretty awesome, but I want to remove 3d models from class selector and also from HUD (bottom left corner). How to achieve this? Thanks.

**Comment by TheStaticVoid** [comment]
to disable them in class selection, go into classselection.res, then CTRL+F and type TFPlayerModel

then change all the xpos and ypos numbers to 9999, this should remove it completely from there.

As for the 3D model in the bottom left, all you have to do is type cl_hud_playerclass_use_playermodel 0 into your console

**Comment by rozhok** [comment]
Thanks dude!
